# Naive-Gaussian Elimination

In [5]:
import numpy as np
from pandas import pivot

A = np.array([[1,1],[2,3]])
y = np.array([[5],[5]])
m = len(A)
n = len(A) + 1
M = np.hstack((A,y))
print(M)
print()
print(Gauss_naive(A,y))

[[1 1 5]
 [2 3 5]]

[[ 1  1  5]
 [ 0  1 -5]]


In [4]:
def Gauss_naive(A,y):
    M = np.hstack((A,y))
    [m,n] = M.shape
    for i in range(0,m-1):
        pivot = M[i,i]
        for j in range(i+1,m):
            mult = M[j,i]/pivot
            M[j,:] = M[j,:]-mult*M[i,:]
    return M